// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrqqvjhpbjomlyghxspr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndycXF2amhwYmpvbWx5Z2h4c3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDUzNjksImV4cCI6MjA2OTQ4MTM2OX0.ntsB8Lo7wrlq8IZmKh3q9llZZbaYrJw_4pvjLkR53jE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});